// Extracted from: https://www.chipverify.com/verilog/verilog-single-port-ram
// Modified to match our requirements

module single_port_sync_ram
  # (parameter ADDR_WIDTH = 4,
     parameter DATA_WIDTH = 32,
     parameter DEPTH = 16
    )

  ( 	input 					clk,
   		input [ADDR_WIDTH-1:0]	addr,
   		input [DATA_WIDTH-1:0]	idata,
   		input 					cs,
   		input 					we,
   		output [DATA_WIDTH-1:0]	odata
  );

  reg [DATA_WIDTH-1:0] 	tmp_data;
  reg [DATA_WIDTH-1:0] 	mem [DEPTH];

  always @ (posedge clk) begin
    if (cs & we)
      mem[addr] <= idata;
  end

  always @ (posedge clk) begin
    if (cs) begin
        if(!we) tmp_data <= mem[addr];
        else    tmp_data <= idata;
    end
  end

  assign odata = tmp_data;
endmodule

// The following are auto-generated
// Invoke them using: ruby src/ellers.rb 3 3

// Autogenerated by: ellers.rb
module maze_rom_3_3 #(
     parameter ADDR_WIDTH = 2,
     parameter DATA_WIDTH = 3
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                             _____
      'd0:     odata <= 'b01001; // | |  _|
      'd1:     odata <= 'b10010; // |_  | |
      default: odata <= 'b10101; // |_____|
      // src/ellers.rb 3 3 406305492
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_5_5 #(
     parameter ADDR_WIDTH = 3,
     parameter DATA_WIDTH = 5
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                                 _________
      'd0:     odata <= 'b001001001; // |  _  |  _|
      'd1:     odata <= 'b110000000; // |_|       |
      'd2:     odata <= 'b010101011; // | | | | |_|
      'd3:     odata <= 'b101101001; // |___| |  _|
      default: odata <= 'b101011101; // |_____|___|
      // src/ellers.rb 5 5 3392012853
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_4_4 #(
     parameter ADDR_WIDTH = 2,
     parameter DATA_WIDTH = 4
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                               _______
      'd0:     odata <= 'b0011001; // |  _|  _|
      'd1:     odata <= 'b0010010; // |  _  | |
      'd2:     odata <= 'b0101110; // | | |_| |
      default: odata <= 'b1010101; // |_______|
      // src/ellers.rb 4 4 2134681316
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_6_6 #(
     parameter ADDR_WIDTH = 3,
     parameter DATA_WIDTH = 6
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                                   ___________
      'd0:     odata <= 'b10010101100; // |_  | | |_  |
      'd1:     odata <= 'b01010101010; // | | | | | | |
      'd2:     odata <= 'b01011001001; // | | |_  |  _|
      'd3:     odata <= 'b01011000110; // | | |_   _| |
      'd4:     odata <= 'b00111000000; // |  _|_      |
      default: odata <= 'b10101011111; // |_______|_|_|
      // src/ellers.rb 6 6 1904046982
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_7_7 #(
     parameter ADDR_WIDTH = 3,
     parameter DATA_WIDTH = 7
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                                     _____________
      'd0:     odata <= 'b0101010110010; // | | | | |_  | |
      'd1:     odata <= 'b0101101010010; // | | |_____  | |
      'd2:     odata <= 'b0100110110100; // | |  _| |___  |
      'd3:     odata <= 'b1001010011010; // |_  | |  _| | |
      'd4:     odata <= 'b0101001001010; // | | |  _  | | |
      'd5:     odata <= 'b0100100100010; // | |  _  |   | |
      default: odata <= 'b1010111111101; // |_____|_|_|___|
      // src/ellers.rb 7 7 2638074282
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_8_8 #(
     parameter ADDR_WIDTH = 3,
     parameter DATA_WIDTH = 8
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                                       _______________
      'd0:     odata <= 'b100000111001100; // |_     _|_  |_  |
      'd1:     odata <= 'b100100110100110; // |_  |  _| |  _| |
      'd2:     odata <= 'b010111001101100; // | | |_|  _| |_  |
      'd3:     odata <= 'b010100111001010; // | | |  _|_  | | |
      'd4:     odata <= 'b000011001101001; // |    _|  _| |  _|
      'd5:     odata <= 'b110001010010001; // |_|   | |  _   _|
      'd6:     odata <= 'b101110000001000; // |___|_      |   |
      default: odata <= 'b101010111111111; // |_______|_|_|_|_|
      // src/ellers.rb 8 8 4023964547
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_9_9 #(
     parameter ADDR_WIDTH = 4,
     parameter DATA_WIDTH = 9
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                                         _________________
      'd0:     odata <= 'b00110000110101010; // |  _|    _| | | | |
      'd1:     odata <= 'b10001111100101100; // |_   _|_|_  | |_  |
      'd2:     odata <= 'b00110100101011010; // |  _| |  _____| | |
      'd3:     odata <= 'b01000011100101001; // | |    _|_  | |  _|
      'd4:     odata <= 'b10110011010110100; // |___|  _| | |___  |
      'd5:     odata <= 'b01001100111001001; // | |  _|  _|_  |  _|
      'd6:     odata <= 'b01010101011001100; // | | | | | |_  |_  |
      'd7:     odata <= 'b01100000000110010; // | |_        |_  | |
      default: odata <= 'b10101111111010101; // |_____|_|_|_______|
      // src/ellers.rb 9 9 2429569019
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_10_10 #(
     parameter ADDR_WIDTH = 4,
     parameter DATA_WIDTH = 10
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                                           ___________________
      'd0:     odata <= 'b1001100101010100101; // |_  |_  | | | |  ___|
      'd1:     odata <= 'b1000000001011000010; // |_        | |_    | |
      'd2:     odata <= 'b1001111110111011010; // |_  |_|_|___|___| | |
      'd3:     odata <= 'b1001010011010011001; // |_  | |  _| |  _|  _|
      'd4:     odata <= 'b1010001100001010110; // |___   _|    _____| |
      'd5:     odata <= 'b0100110011110000001; // | |  _|  _|_|      _|
      'd6:     odata <= 'b0000001101100101001; // |      _| |_  | |  _|
      'd7:     odata <= 'b0111100011000101110; // | |_|_   _|   | |_| |
      'd8:     odata <= 'b0101010011110101010; // | | | |  _|_| | | | |
      default: odata <= 'b1010111010101110101; // |_____|_______|_____|
      // src/ellers.rb 10 10 1048948824
    endcase
  end
endmodule

module maze_rom_only #(
    parameter ADDR_WIDTH = 4,
    parameter DATA_WIDTH = 32
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output [DATA_WIDTH-1:0] odata
);

    generate
        if(/*MAX_MAZE_X == 5*/DATA_WIDTH == 9) begin : rom_5
            maze_rom_5_5 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) rom(.clk(clk), .addr(addr), .odata(odata));
        end else if(/*MAX_MAZE_X == 4*/ DATA_WIDTH == 7) begin : rom_4
            maze_rom_4_4 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) rom(.clk(clk), .addr(addr), .odata(odata));
        end else if(/*MAX_MAZE_X == 3*/ DATA_WIDTH == 5) begin : rom_3
            maze_rom_3_3 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) rom(.clk(clk), .addr(addr), .odata(odata));
        end else if(/*MAX_MAZE_X == 6*/ DATA_WIDTH == 11) begin : rom_6
            maze_rom_6_6 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) rom(.clk(clk), .addr(addr), .odata(odata));
        end else if(/*MAX_MAZE_X == 7*/ DATA_WIDTH == 13) begin : rom_7
            maze_rom_7_7 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) rom(.clk(clk), .addr(addr), .odata(odata));
        end else if(/*MAX_MAZE_X == 8*/ DATA_WIDTH == 15) begin : rom_8
            maze_rom_8_8 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) rom(.clk(clk), .addr(addr), .odata(odata));
        end else if(/*MAX_MAZE_X == 9*/ DATA_WIDTH == 17) begin : rom_9
            maze_rom_9_9 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) rom(.clk(clk), .addr(addr), .odata(odata));
        end else if(/*MAX_MAZE_X == 10*/ DATA_WIDTH == 19) begin : rom_10
            maze_rom_10_10 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(DATA_WIDTH)) rom(.clk(clk), .addr(addr), .odata(odata));
        end
    endgenerate
endmodule

module maze_rom_multi #(
    parameter ADDR_WIDTH = 4,
    parameter DATA_WIDTH = 32,
    parameter MIN_MAZE_X = 3,
    parameter MAX_MAZE_X = 8,
    parameter BITS_MAX_MAZE = 4
)(
    input clk,
    input [BITS_MAX_MAZE-1:0] sel,
    input [ADDR_WIDTH-1:0] addr,
    output [DATA_WIDTH-1:0] odata
);
    wire [DATA_WIDTH-1:0] odatas [0:MAX_MAZE_X];
    genvar i;
    generate
      for(i = 0; i < MIN_MAZE_X; i=i+1) begin : dummy
        assign odatas[i] = 0;
      end
      for(i = MIN_MAZE_X; i <= MAX_MAZE_X; i=i+1) begin : rom_gen
        maze_rom_only #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(i*2-1)) rom(.clk(clk), .addr(addr), .odata(odatas[i]));
      end
    endgenerate
    assign odata = odatas[sel];
endmodule

