// Extracted from: https://www.chipverify.com/verilog/verilog-single-port-ram
// Modified to match our requirements

module single_port_sync_ram
  # (parameter ADDR_WIDTH = 4,
     parameter DATA_WIDTH = 32,
     parameter DEPTH = 16
    )

  ( 	input 					clk,
   		input [ADDR_WIDTH-1:0]	addr,
   		input [DATA_WIDTH-1:0]	idata,
   		input 					cs,
   		input 					we,
   		output [DATA_WIDTH-1:0]	odata
  );

  reg [DATA_WIDTH-1:0] 	tmp_data;
  reg [DATA_WIDTH-1:0] 	mem [DEPTH];

  always @ (posedge clk) begin
    if (cs & we)
      mem[addr] <= idata;
  end

  always @ (posedge clk) begin
    if (cs) begin
        if(!we) tmp_data <= mem[addr];
        else    tmp_data <= idata;
    end
  end

  assign odata = tmp_data;
endmodule

// The following are auto-generated
// Invoke them using: ruby src/ellers.rb 3 3

// Autogenerated by: ellers.rb
module maze_rom_3_3 #(
     parameter ADDR_WIDTH = 2,
     parameter DATA_WIDTH = 3
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                             _____
      'd0:     odata <= 'b01001; // | |  _|
      'd1:     odata <= 'b10010; // |_  | |
      default: odata <= 'b10101; // |_____|
      // src/ellers.rb 3 3 406305492
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_5_5 #(
     parameter ADDR_WIDTH = 3,
     parameter DATA_WIDTH = 5
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                                 _________
      'd0:     odata <= 'b001001001; // |  _  |  _|
      'd1:     odata <= 'b110000000; // |_|       |
      'd2:     odata <= 'b010101011; // | | | | |_|
      'd3:     odata <= 'b101101001; // |___| |  _|
      default: odata <= 'b101011101; // |_____|___|
      // src/ellers.rb 5 5 3392012853
    endcase
  end
endmodule

// Autogenerated by: ellers.rb
module maze_rom_4_4 #(
     parameter ADDR_WIDTH = 2,
     parameter DATA_WIDTH = 4
)(
    input clk,
    input [ADDR_WIDTH-1:0] addr,
    output reg [DATA_WIDTH-1:0] odata
);
  always @(posedge clk) begin
    case (addr)
      //                               _______
      'd0:     odata <= 'b0011001; // |  _|  _|
      'd1:     odata <= 'b0010010; // |  _  | |
      'd2:     odata <= 'b0101110; // | | |_| |
      default: odata <= 'b1010101; // |_______|
      // src/ellers.rb 4 4 2134681316
    endcase
  end
endmodule

module maze_rom #(
    parameter ADDR_WIDTH = 4,
    parameter DATA_WIDTH = 32
)(
    input clk,
    input [1:0] sel,
    input [ADDR_WIDTH-1:0] addr,
    output [DATA_WIDTH-1:0] odata
);
    wire [DATA_WIDTH-1:0] odata_3x3;
    wire [DATA_WIDTH-1:0] odata_4x4;
    wire [DATA_WIDTH-1:0] odata_5x5;
    maze_rom_3_3 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(ADDR_WIDTH)) rom_3_3(.clk(clk), .addr(addr), .odata(odata_3x3));
    maze_rom_4_4 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(ADDR_WIDTH)) rom_4_4(.clk(clk), .addr(addr), .odata(odata_4x4));
    maze_rom_5_5 #(.ADDR_WIDTH(ADDR_WIDTH), .DATA_WIDTH(ADDR_WIDTH)) rom_5_5(.clk(clk), .addr(addr), .odata(odata_5x5));
    assign odata = (sel == 2'b11 ? odata_3x3 : (sel == 2'b00 ? odata_4x4 : odata_5x5));
endmodule